export enum RoleEnum {
  Admin = 'admin',
  Client = 'client',
  Owner = 'owner',
}

export enum RedisKeys {
  ALL_USERS = 'ALL_USERS',
  ALL_USER_DETAILS = 'ALL_USER_DETAILS',
  ALL_USER_TARIFFS = 'ALL_USER_TARIFFS',
  ALL_FILES = 'ALL_FILES',
  ALL_PARKS = 'ALL_PARKS',
  ALL_TRANSACTIONS = 'ALL_TRANSACTIONS',
  ALL_PARK_TARIFFS = 'ALL_PARK_TARIFFS',
  ALL_PARK_PLACES = 'ALL_PARK_PLACES',
  ALL_SERVICES = 'ALL_SERVICES',
  ALL_LAYERS = 'ALL_LAYERS',
}
